name: SonarCloud

on:
  push:
    branches:
      - sonarq-pruebas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # O la versión que uses

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: juanda-mora_ApiMusica
          SONAR_ORGANIZATION: juanda-mora

      - name: Run Tests (opcional)
        run: dotnet test --no-build --verbosity normal
